### ISSUE TITLE
Support runtime configurable paths

### ISSUE THREAD

**Issue by prodrigestivill** [radareorg/radare2#21484]
## Description

In the [radare2 snap version](https://github.com/radareorg/radare2-snap) the installation paths changes on every build install because it is using the classic confinement and the actual installed path changes on runtime.

Currently the following environment variables are set to address this issue:
```yaml
environment:
  R2_LIBR_PLUGINS: "$SNAP/usr/lib/radare2/$SNAP_VERSION"
  R2_MAGICPATH: "$SNAP/usr/share/radare2/$SNAP_VERSION/magic"
  SLEIGHHOME: "$SNAP/usr/lib/radare2/$SNAP_VERSION"
```

With this configuration plugins, sleigh and magic files are loaded correctly.

## First issue: radare2 -H
The first issue would be that the paths changed on runtime currently are not reported back when running `radare2 -H` command, not sure the importance/effects of this.

## Second issue: the rest of share files
The second issue are that radare2 in snap don't load any other file from `/usr/share/radare2/VERSION/*`, example of files not loaded are: charsets, cons, fcnsign, flag, format, hid, opcodes, syscall, www, ...

Inspired on what is observed the `radare2 -H` output a possible solution could be to implemented the use of `R2_PREFIX` env var for those paths, also allowing to remove the now unneeded `R2_MAGICPATH` from the snap environment.

Alternatively adding variables for each non working paths, like the one currently working for `R2_MAGICPATH` could also be a possible solution.

Whatever fits best for the project rest of environments where it is executed.
